vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm build
      - run: apt -y update
      - run: apt -y install python3-pip
      - run: pip3 install boto3 boto ansible
      - run: 
          name: eshop
          command: |
            export AWS_ACCESS_KEY_ID='accesskey'
            export AWS_SECRET_ACCESS_KEY='secretkey'
            export AWS_SECURITY_TOKEN='securitytoken'
            echo "$AWS_ACCESS_KEY_ID"
            echo "$AWS_SECRET_ACCESS_KEY"
            echo "$AWS_SECURITY_TOKEN"
          
workflows:
  version: 2.1
  build:
    jobs:
      - build